apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy-01
  labels:
    app: app2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app-deploy-01
        image: vietaws/eks:v2
        ports:
        - containerPort: 8080
