apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs3
  labels:
    app: app-rs-3
    type: rs
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
        project: demo
    spec:
      containers:
      - name: app3
        image: vietaws/eks:v3
